### ISSUE TITLE
1. 기획 및 설계

### ISSUE THREAD

**Issue by I-mYejin** [I-mYejin/2023OSS_TeamProject#1]
2023-05-07 zoom meeting (4:00~)

**Comment by I-mYejin** [comment]
# 서비스 개요

과제는 여러 개지만 당신은 동시에 여러 과제를 수행할 수 없습니다. 

그렇다면 어떤 과제를 먼저 하시겠습니까? 

대부분의 P들은 마감일이 가장 빠른 과제를 우선시하겠죠.

**그런데 잠깐… 이 과제 마감일이 언제였지..?!**

를 외치는 당신을 위해 “  ”가 알려드릴게요!

취향에 따른 우선순위(마감일, 소요 시간, 과제 받은 날) 리스트는 물론,

당신이 놓치는 과제가 없도록 하루 전에 알림을 드려요!

이제 나에게 허락된 건 A+뿐!

**Comment by EundaChung** [comment]
이름 + 한줄 요약 설명:
1Jung
J가 되고 싶은 P들을 위한, 더 부지런한 J가 되고 싶은 사람을 위한 서비스
개요 및 기획의도: 
다양한 캘린더 앱을 써도 간단하고 명료한 앱이 없어서 결국 메모장을 쓰게 돼 우리에게 딱 맞는 서비스를 구현해보기 위해 개발
부지런해지고 싶은 사람들, 쌓여가는 과제와 할 것들에 치여 다 챙기기 힘들었던 사람들, 막상 다양한 기능들이 있는 앱을 써도 복잡하고 어려워서 누리지 못했던 사람들을 위한 서비스

**Comment by I-mYejin** [comment]
1Jung
주제
- 과제 일정을 관리해주는 프로그램

개요 및 기획의도
- 다양한 캘린더 앱을 써도 간단하고 명료한 앱이 없어서 결국 메모장을 쓰게 돼 우리에게 딱 맞는 서비스를 구현해보기 위해 개발
부지런해지고 싶은 사람들, 쌓여가는 과제와 할 것들에 치여 다 챙기기 힘들었던 사람들, 막상 다양한 기능들이 있는 앱을 써도 복잡하고 어려워서 누리지 못했던 사람들을 위한 서비스

**Comment by I-mYejin** [comment]
# 기능 설명

- 과제 및 일정 추가 기능
    
    (제목, 마감일, 예상소요시)
    
- 우선순위에 따른 리스트 제공
    
     (마감일 빠른 순, 소요시간 많은 순, 소요시간 적은 순, 과제 받은 날짜 순)
    
- 마감일 하루 전 알림 기능 (메일)

**Comment by EundaChung** [comment]
대략적인 기능 설명: 
메인 기능:
데드라인 설정 기능 
지금까지 설정한 할일 목록 프린트 기능
데드라인 수정, 목록 수정 기능
완료, 삭제 기능
검색 기능(과목/시간/날짜별)
부가적인 기능:
알림 기능 → 데드라인 쓰는 파트, 해야할일 쓰는 파트 나누기
missing 일정 보여주기
다가오는 일정 보여주기
자주 추가되는 일정 자동으로 추가 기능(요일 단위로 추가할 수 있도록)
다른 사람이랑 공유 기능 (팀플할때) → 파일을 서로 보내면 읽고 불러올 수 있도록

**Comment by EundaChung** [comment]
+과제 입력을 할 때 예상 소요시간 적을 수 있도록

**Comment by I-mYejin** [comment]
1Jung

주제

- 과제 일정을 관리해주는 프로그램
- 

개요 및 기획의도

- 다양한 캘린더 앱을 써도 간단하고 명료한 앱이 없어서 결국 메모장을 쓰게 돼 우리에게 딱 맞는 서비스를 구현해보기 위해 개발부지런해지고 싶은 사람들, 쌓여가는 과제와 할 것들에 치여 다 챙기기 힘들었던 사람들, 막상 다양한 기능들이 있는 앱을 써도 복잡하고 어려워서 누리지 못했던 사람들을 위한 서비스

기능

메인

- 일정 추가 기능

제목, deadline, 예상 소요 시간 추가

- 일정 삭제 기능

일정 리스트 삭제

- 일정 수정 기능

제목, deadline, 예상 소요 시간 수정

- 일정 완료 기능

일정 리스트 체크 표시

- 일정 리스트 출력 기능

부가적인 기능

- 파일 저장 기능

일정 리스트 txt 파일로 저장

- 파일 불러오기 기능

불러오는 파일 이름 입력

- 일정 요일 단위로 추가 기능 (반복 기능)
- 요일별로 오늘 할 일 추가 기능

**Comment by I-mYejin** [comment]
README.md 파일 개요 및 기획의도까지 추가했어요!
