### ISSUE TITLE
1-1. Wiki page 만들기

### ISSUE THREAD

**Issue by EundaChung** [I-mYejin/2023OSS_TeamProject#5]
내가 직접적인 수정을 할 수 없어서 .md 파일을 보내서 수정하기

**Comment by EundaChung** [comment]
Home.md
#### 2022_01 OSS MiniProject

<p align="center"><img src="https://cdn.pixabay.com/photo/2016/06/20/22/24/robot-1470108_1280.png" height="180px" width="300px"></p>



<div align="center">

### J가 되고 싶은 P들을 위한, 더 부지런한 J가 되고 싶은 사람을 위한 서비스
- - -
과제는 여러 개지만 당신은 동시에 여러 과제를 수행할 수 없습니다.

그렇다면 어떤 과제를 먼저 하시겠습니까?

대부분의 P들은 마감일이 가장 빠른 과제를 우선시하겠죠.

그런데 잠깐… 이 과제 마감일이 언제였지..?!

를 외치는 당신을 위해 1Jung이 당신의 일정을 알려드릴게요!

이제 나에게 허락된 건 불안함 없는 A+뿐!
 
달라진 나의 하루가 기대되지 않나요?
</div>

## 목차

## [Home](Home)

<br/>

## 1. 기능

- ### [서비스상세](서비스상세)


<br/>

## 2. 협업
- ### [개발일지](개발일지)

- ### [프로젝트_참여자](프로젝트_참여자)

 
<br/>

## Made by
- 정은다 [EundaChung GITHUB LINK](https://github.com/EundaChung)
- 임예진 [I-mYejin GITHUB LINK](https://github.com/I-mYejin)

**Comment by EundaChung** [comment]
개발일지.md
<img src="https://cdn.pixabay.com/photo/2012/04/02/13/05/painting-24439_1280.png" height="300px" width="200px">


### 23/05/07 프로젝트 시작
- 프로젝트 개발을 위한 Repo 생성 및 링크 공유
  - Repo Owner: 임예진
  - Contributor: 정은다
- github issue 개설
- 프로젝트 주제 선정
  - 기능 선정
- README.md 파일 작성
- Wiki 페이지 작성

- - -

**Comment by EundaChung** [comment]
프로젝트참여자.md

<p align="center"><img src="https://cdn.pixabay.com/photo/2017/05/18/16/08/stick-people-2324009_1280.png" height="150px" width="300px"></p>

# 임예진 
- 역할 : Repo 관리, 코드 구현 
- GitHub : [I-mYejin](https://github.com/I-mYejin)

# 정은다 
- 역할 : 아이디어 제공, 코드 구현
- GitHub : [EundaChung](https://github.com/EundaChung)

**Comment by I-mYejin** [comment]
확인해서 업로드했어요!

**Comment by I-mYejin** [comment]
wiki 서비스 상세 페이지 만들었습니다!

**Comment by EundaChung** [comment]
개발일지
1주차: ~23/05/07 프로젝트 시작
* 프로젝트 개발을 위한 Repo 생성 및 링크 공유
    * Repo Owner: 임예진
    * Contributor: 정은다
* github issue 개설
* 프로젝트 주제 선정
    * 기능 선정
* README.md 파일 작성
* Wiki 페이지 작성

2주차: ~23/05/14 프로젝트 진행
* CRUD 구현을 위해 설계한 모든 기능에 대해 적절히 분배
    * 임예진
        * 일정 삭제 기능
            * 일정 리스트 삭제
        * 일정 완료 기능
            * 일정 리스트 체크 표시
        * 일정 리스트 출력 기능
        * 요일별로 오늘 할 일 추가 기능
    * 정은다
        * 일정 추가 기능
            * 제목, deadline, 예상 소요 시간 추가
        * 파일 저장 기능
            * 일정 리스트 txt 파일로 저장
        * 파일 불러오기 기능
            * 불러오는 파일 이름 입력
        * 일정 요일 단위로 추가 기능 (반복 기능)
        * 일정 수정 기능
            * 제목, deadline, 예상 소요 시간 수정
* 구조체 완성
* 함수 구현

3주차: ~23/05/21 프로젝트 완성
* 함수 구현 및 테스트
* 코드 추가, 수정, 삭제 
* 개발 완료: 전체 프로그램 실행, 구현 및 WIKI Page 완성
