### ISSUE TITLE
2. CRUD 구현

### ISSUE THREAD

**Issue by EundaChung** [I-mYejin/2023OSS_TeamProject#6]
"Team project에서 설계한 모든 기능에 대해 팀원끼리 적절히 분배하여 구현 및 테스트하고,
 코드에 대한 추가, 수정, 삭제 작업이 있을 때마다 git을 이용하여 버전을 관리하며 개발하고,
 github에 개발에 대한 작업들을 계속 업데이트하면서 프로젝트를 완성해 갑니다."

<현재 구현해야할 기능들 파트 배분>
-정은다-
* 일정 추가 기능
    * 제목, deadline, 예상 소요 시간 추가
* 파일 저장 기능
    * 일정 리스트 txt 파일로 저장
* 파일 불러오기 기능
    * 불러오는 파일 이름 입력
* 일정 요일 단위로 추가 기능 (반복 기능)
* 일정 수정 기능
    * 제목, deadline, 예상 소요 시간 수정

-임예진-
* 일정 삭제 기능
    * 일정 리스트 삭제
* 일정 완료 기능
    * 일정 리스트 체크 표시
* 일정 리스트 출력 기능
* 요일별로 오늘 할 일 추가 기능

**Comment by EundaChung** [comment]
main():
- selectMenu()

**Comment by EundaChung** [comment]
출력 기능에 요일별로(deadline) 일정 + 오늘 할 일 출력할 수 있도록
아마 search 기능도 필요할수도!!

**Comment by I-mYejin** [comment]
일정 추가 기능 (제목/데드라인/예상소요시간 추가)
일정 삭제
일정 수정
일정 완료 
일정 리스트 출력 (예상소요시간/데드라인)
파일 저장
파일 불러오기

최종기능
